import { IPhoneItem } from './types';

export const itemsFlagDropdown: IPhoneItem[] = [
	{
		id: 1,
		icon: 'flag_united_states',
		code: '+1',
		iso: 'US',
		text: '+1 (___)___-____',
		mask: '+# (###)###-####',
	},
	{
		id: 2,
		icon: 'flag_united_kingdom',
		code: '+44',
		iso: 'GB',
		text: '+44 __-____-____',
		mask: '+## ##-####-####',
	},
	{
		id: 3,
		icon: 'flag_ukraine',
		code: '+380',
		iso: 'UA',
		text: '+38 (0__) ___-__-__',
		mask: '+## (###) ###-##-##',
	},
	{
		id: 4,
		icon: 'flag_slovenia',
		code: '+386',
		iso: 'SI',
		text: '+386 __-___-___',
		mask: '+### ##-###-###',
	},
	{
		id: 5,
		icon: 'flag_saudi_arabia',
		code: '+966',
		iso: 'SA',
		text: '+966 _-___-____',
		mask: '+### #-###-####',
	},
	{
		id: 6,
		icon: 'flag_portugal',
		code: '+351',
		iso: 'PT',
		text: '+351 __-___-____',
		mask: '+### ##-###-####',
	},
	{
		id: 7,
		icon: 'flag_argentina',
		code: '+54',
		iso: 'AR',
		text: '+54 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 8,
		icon: 'flag_austria',
		code: '+43',
		iso: 'AT',
		text: '+43 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 9,
		icon: 'flag_azerbaijan',
		code: '+994',
		iso: 'AZ',
		text: '+994 __-___-__-__',
		mask: '+### ##-###-##-##',
	},
	{
		id: 10,
		icon: 'flag_bahrain',
		code: '+973',
		iso: 'BH',
		text: '+973 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 11,
		icon: 'flag_belarus',
		code: '+375',
		iso: 'BY',
		text: '+375 (__)___-__-__',
		mask: '+### (##)###-##-##',
	},
	{
		id: 12,
		icon: 'flag_belgium',
		code: '+32',
		iso: 'BE',
		text: '+32 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 13,
		icon: 'flag_bosnia_and_herzegovina',
		iso: 'BA',
		code: '+387',
		text: '+387 __-____',
		mask: '+### ##-####',
	},
	{
		id: 14,
		icon: 'flag_brazil',
		code: '+55',
		iso: 'BR',
		text: '+55 (__)____-____',
		mask: '+## (##)####-####',
	},
	{
		id: 15,
		icon: 'flag_british_columbia',
		code: '+246',
		iso: 'IO',
		text: '+246 ___-____',
		mask: '+### ###-####',
	},
	{
		id: 16,
		icon: 'flag_bulgaria',
		code: '+359',
		iso: 'BG',
		text: '+359 (___)___-___',
		mask: '+### (###)###-###',
	},
	{
		id: 17,
		icon: 'flag_canada',
		code: '+1',
		iso: 'CA',
		text: '+1 (__)___-____',
		mask: '+# (##)###-####',
	},
	{
		id: 18,
		icon: 'flag_chile',
		code: '+56',
		iso: 'CL',
		text: '+56 _-____-____',
		mask: '+## #-####-####',
	},
	{
		id: 19,
		icon: 'flag_china',
		code: '+86',
		iso: 'CN',
		text: '+86 (___)____-___',
		mask: '+## (###)####-###',
	},
	{
		id: 20,
		icon: 'flag_colombia',
		code: '+57',
		iso: 'CO',
		text: '+57 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 21,
		icon: 'flag_costa_rica',
		code: '+506',
		iso: 'CR',
		text: '+506 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 22,
		icon: 'flag_croatia',
		code: '+385',
		iso: 'HR',
		text: '+385 __-___-___',
		mask: '+### ##-###-###',
	},
	{
		id: 23,
		icon: 'flag_cuba',
		code: '+53',
		iso: 'CU',
		text: '+53 _-___-____',
		mask: '+## #-###-####',
	},
	{
		id: 24,
		icon: 'flag_czech_republic',
		code: '+420',
		iso: 'CZ',
		text: '+420 (___)___-___',
		mask: '+### (###)###-###',
	},
	{
		id: 25,
		icon: 'flag_denmark',
		code: '+45',
		iso: 'DK',
		text: '+45 __-__-__-__',
		mask: '+## ##-##-##-##',
	},
	{
		id: 26,
		icon: 'flag_dominican_republic',
		code: '+1',
		iso: 'DO',
		text: '+1 (___)___-____',
		mask: '+# (###)###-####',
	},
	{
		id: 27,
		icon: 'flag_ecuador',
		code: '+593',
		iso: 'EC',
		text: '+593 _-___-____',
		mask: '+### #-###-####',
	},
	{
		id: 28,
		icon: 'flag_egypt',
		code: '+20',
		iso: 'EG',
		text: '+20 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 29,
		icon: 'flag_el_salvador',
		code: '+503',
		iso: 'SV',
		text: '+503 __-__-____',
		mask: '+### ##-##-####',
	},
	{
		id: 30,
		icon: 'flag_finland',
		code: '+358',
		iso: 'FI',
		text: '+358 (___)___-__-__',
		mask: '+### (###)###-##-##',
	},
	{
		id: 31,
		icon: 'flag_france',
		code: '+33',
		iso: 'FR',
		text: '+33 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 32,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 ___-___',
		mask: '+## ###-###',
	},
	{
		id: 33,
		icon: 'flag_greece',
		code: '+30',
		iso: 'GR',
		text: '+30 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 34,
		icon: 'flag_hong_kong',
		code: '+852',
		iso: 'HK',
		text: '+852 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 35,
		icon: 'flag_hungary',
		code: '+36',
		iso: 'HU',
		text: '+36 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 36,
		icon: 'flag_india',
		code: '+91',
		iso: 'IN',
		text: '+91 (____)___-___',
		mask: '+## (####)###-###',
	},
	{
		id: 37,
		icon: 'flag_indonesia',
		code: '+62',
		iso: 'ID',
		text: '+62 __-___-__',
		mask: '+## ##-###-##',
	},
	{
		id: 38,
		icon: 'flag_ireland',
		code: '+353',
		iso: 'IE',
		text: '+353 (___)___-___',
		mask: '+### (###)###-###',
	},
	{
		id: 39,
		icon: 'flag_italy',
		code: '+39',
		iso: 'IT',
		text: '+39 (___)____-___',
		mask: '+## (###)####-###',
	},
	{
		id: 40,
		icon: 'flag_japan',
		code: '+81',
		iso: 'JP',
		text: '+81 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 41,
		icon: 'flag_kazakhstan',
		code: '+7',
		iso: 'KZ',
		text: '+7 (___)___-__-__',
		mask: '+# (###)###-##-##',
	},
	{
		id: 42,
		icon: 'flag_kuwait',
		code: '+965',
		iso: 'KW',
		text: '+965 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 43,
		icon: 'flag_malaysia',
		code: '+60',
		iso: 'MY',
		text: '+60 _-___-___',
		mask: '+## #-###-###',
	},
	{
		id: 44,
		icon: 'flag_mexico',
		code: '+52',
		iso: 'MX',
		text: '+52 __-__-____',
		mask: '+## ##-##-####',
	},
	{
		id: 45,
		icon: 'flag_morocco',
		code: '+212',
		iso: 'MA',
		text: '+212 __-____-___',
		mask: '+### ##-####-###',
	},
	{
		id: 46,
		icon: 'flag_netherlands',
		code: '+31',
		iso: 'NL',
		text: '+31 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 47,
		icon: 'flag_new_zealand',
		code: '+64',
		iso: 'NZ',
		text: '+64 _-___-___',
		mask: '+## #-###-###',
	},
	{
		id: 48,
		icon: 'flag_nigeria',
		code: '+234',
		iso: 'NG',
		text: '+234 __-___-__',
		mask: '+### ##-###-##',
	},
	{
		id: 49,
		icon: 'flag_norway',
		code: '+47',
		iso: 'NO',
		text: '+47 (___)__-___',
		mask: '+## (###)##-###',
	},
	{
		id: 50,
		icon: 'flag_pakistan',
		code: '+92',
		iso: 'PK',
		text: '+92 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 51,
		icon: 'flag_peru',
		code: '+51',
		iso: 'PE',
		text: '+51 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 52,
		icon: 'flag_philippines',
		code: '+63',
		iso: 'PH',
		text: '+63 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 53,
		icon: 'flag_poland',
		code: '+48',
		iso: 'PL',
		text: '+48 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 54,
		icon: 'flag_puerto_rico',
		code: '+1',
		iso: 'PR',
		text: '+1 (___) ___ ____',
		mask: '+# (###) ### ####',
	},
	{
		id: 55,
		icon: 'flag_qatar',
		code: '+974',
		iso: 'QA',
		text: '+974 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 56,
		icon: 'flag_romania',
		code: '+40',
		iso: 'RO',
		text: '+40 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 57,
		icon: 'flag_russia',
		code: '+7',
		iso: 'RU',
		text: '+7 (___)___-__-__',
		mask: '+# (###)###-##-##',
	},
	{
		id: 58,
		icon: 'flag_saudi_arabia',
		code: '+966',
		iso: 'SA',
		text: '+966 __-____-____',
		mask: '+### ##-####-####',
	},
	{
		id: 59,
		icon: 'flag_serbia',
		code: '+381',
		iso: 'RS',
		text: '+381 __-___-____',
		mask: '+### ##-###-####',
	},
	{
		id: 60,
		icon: 'flag_singapore',
		code: '+65',
		iso: 'SG',
		text: '+65 ____-____',
		mask: '+## ####-####',
	},
	{
		id: 61,
		icon: 'flag_slovenia',
		code: '+386',
		iso: 'SL',
		text: '+386 __-___-___',
		mask: '+### ##-###-###',
	},
	{
		id: 62,
		icon: 'flag_south_africa',
		code: '+27',
		iso: 'ZA',
		text: '+27 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 63,
		icon: 'flag_south_korea',
		code: '+82',
		iso: 'KR',
		text: '+82 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 64,
		icon: 'flag_spain',
		code: '+34',
		iso: 'ES',
		text: '+34 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 65,
		icon: 'flag_sweden',
		code: '+46',
		iso: 'SE',
		text: '+46 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 66,
		icon: 'flag_switzerland',
		code: '+41',
		iso: 'CH',
		text: '+41 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 67,
		icon: 'flag_taiwan',
		code: '+886',
		iso: 'TW',
		text: '+886 ____-____',
		mask: '+### ####-####',
	},
	{
		id: 68,
		icon: 'flag_thailand',
		code: '+66',
		iso: 'TH',
		text: '+66 __-___-___',
		mask: '+## ##-###-###',
	},
	{
		id: 69,
		icon: 'flag_turkey',
		code: '+90',
		iso: 'TR',
		text: '+90 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 70,
		icon: 'flag_united_arab_emirates',
		code: '+971',
		iso: 'AE',
		text: '+971 _-___-____',
		mask: '+### #-###-####',
	},
	{
		id: 71,
		icon: 'flag_uruguay',
		code: '+598',
		iso: 'UY',
		text: '+598 _-___-__-__',
		mask: '+### #-###-##-##',
	},
	{
		id: 72,
		icon: 'flag_uzbekistan',
		code: '+998',
		iso: 'UZ',
		text: '+998 __-___-____',
		mask: '+### ##-###-####',
	},
	{
		id: 73,
		icon: 'flag_venezuela',
		code: '+58',
		iso: 'VE',
		text: '+58 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 74,
		icon: 'flag_australia',
		code: '+61',
		iso: 'AU',
		text: '+61 _-____-____',
		mask: '+## #-####-####',
	},
	{
		id: 75,
		icon: 'flag_bosnia_and_herzegovina',
		iso: 'BA',
		code: '+387',
		text: '+387 __-_____',
		mask: '+### ##-#####',
	},
	{
		id: 76,
		icon: 'flag_brazil',
		code: '+55',
		iso: 'BR',
		text: '+55 (__)_____-____',
		mask: '+## (##)#####-####',
	},
	{
		id: 77,
		icon: 'flag_china',
		code: '+86',
		iso: 'CN',
		text: '+86 (___)____-____',
		mask: '+## (###)####-####',
	},
	{
		id: 78,
		icon: 'flag_china',
		code: '+86',
		iso: 'CN',
		text: '+86 __-_____-_____',
		mask: '+## ##-#####-#####',
	},
	{
		id: 79,
		icon: 'flag_ecuador',
		code: '+593',
		iso: 'EC',
		text: '+593 __-___-____',
		mask: '+### ##-###-####',
	},
	{
		id: 80,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 (___)__-__',
		mask: '+## (###)##-##',
	},
	{
		id: 81,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 (___)__-___',
		mask: '+## (###)##-###',
	},
	{
		id: 82,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 (___)__-____',
		mask: '+## (###)##-####',
	},
	{
		id: 83,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 84,
		icon: 'flag_germany',
		code: '+49',
		iso: 'DE',
		text: '+49 (____)___-____',
		mask: '+## (####)###-####',
	},
	{
		id: 85,
		icon: 'flag_indonesia',
		code: '+62',
		iso: 'ID',
		text: '+62 __-___-___',
		mask: '+## ##-###-###',
	},
	{
		id: 86,
		icon: 'flag_indonesia',
		code: '+62',
		iso: 'ID',
		text: '+62 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 87,
		icon: 'flag_indonesia',
		code: '+62',
		iso: 'ID',
		text: '+62 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 88,
		icon: 'flag_indonesia',
		code: '+62',
		iso: 'ID',
		text: '+62 (___)___-__-___',
		mask: '+## (###)###-##-###',
	},
	{
		id: 89,
		icon: 'flag_japan',
		code: '+81',
		iso: 'JP',
		text: '+81 __-____-____',
		mask: '+## ##-####-####',
	},
	{
		id: 90,
		icon: 'flag_malaysia',
		code: '+60',
		iso: 'MY',
		text: '+60 __-___-___',
		mask: '+## ##-###-###',
	},
	{
		id: 91,
		icon: 'flag_malaysia',
		code: '+60',
		iso: 'MY',
		text: '+60 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 92,
		icon: 'flag_malaysia',
		code: '+60',
		iso: 'MY',
		text: '+60 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 93,
		icon: 'flag_mexico',
		code: '+52',
		iso: 'MX',
		text: '+52 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 94,
		icon: 'flag_new_zealand',
		code: '+64',
		iso: 'NZ',
		text: '+64 (___)___-___',
		mask: '+## (###)###-###',
	},
	{
		id: 95,
		icon: 'flag_new_zealand',
		code: '+64',
		iso: 'NZ',
		text: '+64 (___)___-____',
		mask: '+## (###)###-####',
	},
	{
		id: 96,
		icon: 'flag_nigeria',
		code: '+234',
		iso: 'NG',
		text: '+234 __-___-___',
		mask: '+### ##-###-###',
	},
	{
		id: 97,
		icon: 'flag_nigeria',
		code: '+234',
		iso: 'NG',
		text: '+234 (___)___-____',
		mask: '+### (###)###-####',
	},
	{
		id: 98,
		icon: 'flag_taiwan',
		code: '+886',
		iso: 'TW',
		text: '+886 _-____-____',
		mask: '+### #-####-####',
	},
	{
		id: 99,
		icon: 'flag_thailand',
		code: '+66',
		iso: 'TH',
		text: '+66 __-___-____',
		mask: '+## ##-###-####',
	},
	{
		id: 100,
		icon: 'flag_united_arab_emirates',
		code: '+971',
		iso: 'AE',
		text: '+971 __-___-____',
		mask: '+### ##-###-####',
	},
];

export const INITIAL: IPhoneItem = itemsFlagDropdown[0];
